name: CI

# 触发工作流程的事件
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# 按顺序运行作业
jobs:
  npm_pub:
    # 指定的运行器环境
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.0
      - name: Install modules
        run: pnpm install
      # 执行构建步骤
      - name: 构建
        run: pnpm build
      # 发布
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
  codecov:
    # 指定的运行器环境
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.0
      - name: Install modules
        run: pnpm install
      # 生成测试覆盖率
      - name: Run Test Coverage
        run: npx vitest --coverage
      # 生成pr报告
      - name: Report Coverage
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v1
      # 上传到codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
